" Name:         Modus
" Description:  A port of the Emacs Modus themes by Protesilaos Stavrou (https://protesilaos.com/emacs/modus-themes). Based on work by Miika Nissi (https://miikanissi.com/blog/modus-themes-for-neovim/).
" Author:       Christopher Green <cgreen@saguaro.space>
" Maintainer:   Christopher Green <cgreen@saguaro.space>
" Website:      https://saguaro.space
" License:      MIT License
" Last Change:  2024 Oct 13

" Generated by Colortemplate v2.2.3

hi clear
let g:colors_name = 'modus'

let s:t_Co = has('gui_running') ? -1 : (&t_Co ?? 0)
let s:italics = has('gui_running') || (&t_ZH != '' && &t_ZH != '[7m' && !has('win32'))

hi! link Added diffAdded
hi! link Boolean Constant
hi! link Character Constant
hi! link Changed diffChanged
hi! link Conditional Statement
hi! link CurSearch IncSearch
hi! link CursorLineFold FoldColumn
hi! link CursorLineSign SignColumn
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link LineNrAbove LineNr
hi! link LineNrBelow LineNr
hi! link Macro PreProc
hi! link MessageWindow WarningMsg
hi! link Number Constant
hi! link Operator Statement
hi! link PmenuKind Pmenu
hi! link PmenuKindSel PmenuSel
hi! link PmenuExtra Pmenu
hi! link PmenuExtraSel PmenuSel
hi! link PmenuMatch Pmenu
hi! link PmenuMatchSel PmenuSel
hi! link PopupNotification WarningMsg
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Removed diffRemoved
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link StorageClass Type
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link debugBreakpoint SignColumn
hi! link debugPC SignColumn
hi! link lCursor Cursor

if &background ==# 'dark'
  if (has('termguicolors') && &termguicolors) || has('gui_running')
    let g:terminal_ansi_colors = ['#000000', '#ff5f59', '#44bc44', '#d0bc00', '#2fafff', '#feacd0', '#00d3d0', '#ffffff', '#0f0f0f', '#ff6b55', '#70b900', '#fec43f', '#79a8ff', '#f78fe7', '#4ae2f0', '#c6daff']
  endif
  if get(g:, 'modus_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#ffffff guibg=#000000 gui=NONE cterm=NONE
    hi Terminal guifg=#ffffff guibg=#000000 gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=#ffffff guibg=#000000 gui=NONE cterm=NONE
  hi Conceal guifg=#d2b580 guibg=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#000000 guibg=#db7b5f gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#2f3849 gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#2f3849 gui=NONE cterm=NONE
  hi CursorLineNr guifg=#f4f4f4 guibg=#303030 gui=NONE cterm=NONE
  hi DiffAdd guifg=#a0e0a0 guibg=#00381f gui=NONE cterm=NONE
  hi DiffChange guifg=#efef80 guibg=#363300 gui=NONE cterm=NONE
  hi DiffDelete guifg=#ffbfbf guibg=#4f1119 gui=NONE cterm=NONE
  hi DiffText guifg=#efef80 guibg=#363300 gui=NONE cterm=NONE
  hi Directory guifg=#2fafff guibg=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#ffffff guibg=#9d1f1f gui=NONE cterm=NONE
  hi FoldColumn guifg=#bfc0c4 guibg=#282828 gui=NONE cterm=NONE
  hi Folded guifg=#88ca9f guibg=#1e1e1e gui=italic cterm=italic
  hi IncSearch guifg=#ffffff guibg=#7a6100 gui=standout cterm=reverse
  hi LineNr guifg=#989898 guibg=#1e1e1e gui=NONE cterm=NONE
  hi MatchParen guifg=#ffffff guibg=#2f7f9f gui=NONE cterm=NONE
  hi ModeMsg guifg=#989898 guibg=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#2fafff guibg=NONE gui=NONE cterm=NONE
  hi NonText guifg=#989898 guibg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#f4f4f4 guibg=#303030 gui=NONE cterm=NONE
  hi PmenuSbar guifg=#000000 guibg=#989898 gui=NONE cterm=NONE
  hi PmenuSel guifg=#ffffff guibg=#1e1e1e gui=reverse cterm=reverse
  hi PmenuThumb guifg=#ffffff guibg=#000000 gui=NONE cterm=NONE
  hi Question guifg=#2fafff guibg=NONE gui=NONE cterm=NONE
  hi Search guifg=#ffffff guibg=#2f822f gui=NONE cterm=NONE
  hi SignColumn guifg=#989898 guibg=#1e1e1e gui=NONE cterm=NONE
  hi SpecialKey guifg=#989898 guibg=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#ff5f5f guibg=NONE guisp=#ff5f5f gui=NONE cterm=NONE
  hi SpellCap guifg=#efef00 guibg=NONE guisp=#efef00 gui=NONE cterm=NONE
  hi SpellLocal guifg=#82b0ec guibg=NONE guisp=#82b0ec gui=NONE cterm=NONE
  hi SpellRare guifg=#88ca9f guibg=NONE guisp=#88ca9f gui=NONE cterm=NONE
  hi StatusLine guifg=#f0f0f0 guibg=#404040 gui=NONE cterm=NONE
  hi StatusLineNC guifg=#969696 guibg=#2d2d2d gui=NONE cterm=NONE
  hi TabLine guifg=#f7f7f7 guibg=#545454 gui=NONE cterm=NONE
  hi TabLineFill guifg=#989898 guibg=#313131 gui=NONE cterm=NONE
  hi TabLineSel guifg=#ffffff guibg=#000000 gui=NONE cterm=NONE
  hi Title guifg=#c6daff guibg=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#646464 guibg=#646464 gui=NONE cterm=NONE
  hi Visual guifg=#000000 guibg=#c6daff gui=NONE cterm=NONE
  hi VisualNOS guifg=#ffffff guibg=#caa6df gui=NONE cterm=NONE
  hi WarningMsg guifg=#ff9580 guibg=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#000000 guibg=#fec43f gui=NONE cterm=NONE
  hi Comment guifg=#989898 guibg=NONE gui=italic cterm=italic
  hi Constant guifg=#f78fe7 guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#ffffff guibg=#9d1f1f gui=reverse cterm=reverse
  hi Identifier guifg=#00d3d0 guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#ff7f9f guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#6ae4b9 guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#b6a0ff guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#feacd0 guibg=NONE gui=bold cterm=bold
  hi Type guifg=#6ae4b9 guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#c6daff guibg=NONE gui=NONE cterm=NONE
  hi String guifg=#2fafff guibg=NONE gui=NONE cterm=NONE
  hi Quote guifg=#9ac8e0 guibg=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=#ffffff guibg=#000000 gui=NONE cterm=NONE
  hi ToolbarLine guifg=#989898 guibg=#646464 gui=NONE cterm=NONE
  hi ToolbarButton guifg=#000000 guibg=#c4c4c4 gui=bold cterm=bold
  hi jsObjectKey guifg=#f78fe7 guibg=NONE gui=NONE cterm=NONE
  hi jsObjectValue guifg=#caa6df guibg=NONE gui=NONE cterm=NONE
  hi jsObjectProp guifg=#88ca9f guibg=NONE gui=NONE cterm=NONE
  hi jsTemplateExpression guifg=#6ae4b9 guibg=NONE gui=NONE cterm=NONE
  hi jsModuleKeyword guifg=#88ca9f guibg=NONE gui=NONE cterm=NONE
  hi javaScriptParens guifg=#4ae2f0 guibg=NONE gui=NONE cterm=NONE
  hi jsTemplateBraces guifg=#dfaf7a guibg=NONE gui=NONE cterm=NONE
  hi jsDestructuringBraces guifg=#dfaf7a guibg=NONE gui=NONE cterm=NONE
  hi jsBrackets guifg=#dfaf7a guibg=NONE gui=NONE cterm=NONE
  hi jsBraces guifg=#dfaf7a guibg=NONE gui=NONE cterm=NONE
  hi jsParens guifg=#dfaf7a guibg=NONE gui=NONE cterm=NONE
  hi jsFuncParens guifg=#dfaf7a guibg=NONE gui=NONE cterm=NONE
  hi jsClassBraces guifg=#dfaf7a guibg=NONE gui=NONE cterm=NONE
  hi jsFuncBraces guifg=#dfaf7a guibg=NONE gui=NONE cterm=NONE
  hi jsObjectBraces guifg=#dfaf7a guibg=NONE gui=NONE cterm=NONE
  hi jsRepeatBraces guifg=#dfaf7a guibg=NONE gui=NONE cterm=NONE
  hi jsIfElseBraces guifg=#dfaf7a guibg=NONE gui=NONE cterm=NONE
  hi jsTryCatchBraces guifg=#dfaf7a guibg=NONE gui=NONE cterm=NONE
  hi jsVariableDef guifg=#f78fe7 guibg=NONE gui=NONE cterm=NONE
  hi NERDTreeFile guifg=#6ae4b9 guibg=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
  endif
else
  " Light background
  if (has('termguicolors') && &termguicolors) || has('gui_running')
    let g:terminal_ansi_colors = ['#ffffff', '#a60000', '#006800', '#6f5500', '#0031a9', '#721045', '#005e8b', '#000000', '#f0f0f0', '#972500', '#316500', '#884900', '#3548cf', '#8f0075', '#3f578f', '#193668']
  endif
  if get(g:, 'modus_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#000000 guibg=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
    hi Terminal guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi Conceal guifg=#624416 guibg=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#ffffff guibg=#8a290f gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#d0d6ec gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#d0d6ec gui=NONE cterm=NONE
  hi CursorLineNr guifg=#0a0a0a guibg=#e0e0e0 gui=NONE cterm=NONE
  hi DiffAdd guifg=#005000 guibg=#c1f2d1 gui=NONE cterm=NONE
  hi DiffChange guifg=#553d00 guibg=#ffdfa9 gui=NONE cterm=NONE
  hi DiffDelete guifg=#8f1313 guibg=#ffd8d5 gui=NONE cterm=NONE
  hi DiffText guifg=#553d00 guibg=#ffdfa9 gui=NONE cterm=NONE
  hi Directory guifg=#0031a9 guibg=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#000000 guibg=#ff8f88 gui=NONE cterm=NONE
  hi FoldColumn guifg=#404148 guibg=#e9e9e9 gui=NONE cterm=NONE
  hi Folded guifg=#2a5045 guibg=#f2f2f2 gui=italic cterm=italic
  hi IncSearch guifg=#000000 guibg=#f3d000 gui=standout cterm=reverse
  hi LineNr guifg=#595959 guibg=#f2f2f2 gui=NONE cterm=NONE
  hi MatchParen guifg=#000000 guibg=#5fcfff gui=NONE cterm=NONE
  hi ModeMsg guifg=#595959 guibg=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#0031a9 guibg=NONE gui=NONE cterm=NONE
  hi NonText guifg=#595959 guibg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#0a0a0a guibg=#e0e0e0 gui=NONE cterm=NONE
  hi PmenuSbar guifg=#ffffff guibg=#595959 gui=NONE cterm=NONE
  hi PmenuSel guifg=#000000 guibg=#f2f2f2 gui=reverse cterm=reverse
  hi PmenuThumb guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi Question guifg=#0031a9 guibg=NONE gui=NONE cterm=NONE
  hi Search guifg=#000000 guibg=#8adf80 gui=NONE cterm=NONE
  hi SignColumn guifg=#595959 guibg=#f2f2f2 gui=NONE cterm=NONE
  hi SpecialKey guifg=#595959 guibg=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#d00000 guibg=NONE guisp=#d00000 gui=NONE cterm=NONE
  hi SpellCap guifg=#808000 guibg=NONE guisp=#808000 gui=NONE cterm=NONE
  hi SpellLocal guifg=#003497 guibg=NONE guisp=#003497 gui=NONE cterm=NONE
  hi SpellRare guifg=#2a5045 guibg=NONE guisp=#2a5045 gui=NONE cterm=NONE
  hi StatusLine guifg=#0a0a0a guibg=#c8c8c8 gui=NONE cterm=NONE
  hi StatusLineNC guifg=#585858 guibg=#e6e6e6 gui=NONE cterm=NONE
  hi TabLine guifg=#333333 guibg=#c2c2c2 gui=NONE cterm=NONE
  hi TabLineFill guifg=#595959 guibg=#dfdfdf gui=NONE cterm=NONE
  hi TabLineSel guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi Title guifg=#193668 guibg=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#9f9f9f guibg=#9f9f9f gui=NONE cterm=NONE
  hi Visual guifg=#ffffff guibg=#193668 gui=NONE cterm=NONE
  hi VisualNOS guifg=#000000 guibg=#7c318f gui=NONE cterm=NONE
  hi WarningMsg guifg=#7f0000 guibg=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#ffffff guibg=#884900 gui=NONE cterm=NONE
  hi Comment guifg=#595959 guibg=NONE gui=italic cterm=italic
  hi Constant guifg=#8f0075 guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#000000 guibg=#ff8f88 gui=reverse cterm=reverse
  hi Identifier guifg=#005e8b guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#a0132f guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#005f5f guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#531ab6 guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#721045 guibg=NONE gui=bold cterm=bold
  hi Type guifg=#005f5f guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#193668 guibg=NONE gui=NONE cterm=NONE
  hi String guifg=#0031a9 guibg=NONE gui=NONE cterm=NONE
  hi Quote guifg=#005077 guibg=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi ToolbarLine guifg=#595959 guibg=#9f9f9f gui=NONE cterm=NONE
  hi ToolbarButton guifg=#ffffff guibg=#3b3b3b gui=bold cterm=bold
  hi jsObjectKey guifg=#8f0075 guibg=NONE gui=NONE cterm=NONE
  hi jsObjectValue guifg=#7c318f guibg=NONE gui=NONE cterm=NONE
  hi jsObjectProp guifg=#2a5045 guibg=NONE gui=NONE cterm=NONE
  hi jsTemplateExpression guifg=#005f5f guibg=NONE gui=NONE cterm=NONE
  hi jsModuleKeyword guifg=#2a5045 guibg=NONE gui=NONE cterm=NONE
  hi javaScriptParens guifg=#3f578f guibg=NONE gui=NONE cterm=NONE
  hi jsTemplateBraces guifg=#7a4f2f guibg=NONE gui=NONE cterm=NONE
  hi jsDestructuringBraces guifg=#7a4f2f guibg=NONE gui=NONE cterm=NONE
  hi jsBrackets guifg=#7a4f2f guibg=NONE gui=NONE cterm=NONE
  hi jsBraces guifg=#7a4f2f guibg=NONE gui=NONE cterm=NONE
  hi jsParens guifg=#7a4f2f guibg=NONE gui=NONE cterm=NONE
  hi jsFuncParens guifg=#7a4f2f guibg=NONE gui=NONE cterm=NONE
  hi jsClassBraces guifg=#7a4f2f guibg=NONE gui=NONE cterm=NONE
  hi jsFuncBraces guifg=#7a4f2f guibg=NONE gui=NONE cterm=NONE
  hi jsObjectBraces guifg=#7a4f2f guibg=NONE gui=NONE cterm=NONE
  hi jsRepeatBraces guifg=#7a4f2f guibg=NONE gui=NONE cterm=NONE
  hi jsIfElseBraces guifg=#7a4f2f guibg=NONE gui=NONE cterm=NONE
  hi jsTryCatchBraces guifg=#7a4f2f guibg=NONE gui=NONE cterm=NONE
  hi jsVariableDef guifg=#8f0075 guibg=NONE gui=NONE cterm=NONE
  hi NERDTreeFile guifg=#005f5f guibg=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
  endif
endif

if s:t_Co >= 256
  if &background ==# 'dark'
    if get(g:, 'modus_transp_bg', 0)
      hi Normal ctermfg=231 ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=231 ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=231 ctermbg=16 cterm=NONE
      hi Terminal ctermfg=231 ctermbg=16 cterm=NONE
    endif
    hi ColorColumn ctermfg=231 ctermbg=16 cterm=NONE
    hi Conceal ctermfg=179 ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=16 ctermbg=173 cterm=NONE
    hi CursorColumn ctermfg=NONE ctermbg=237 cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=237 cterm=NONE
    hi CursorLineNr ctermfg=255 ctermbg=236 cterm=NONE
    hi DiffAdd ctermfg=114 ctermbg=23 cterm=NONE
    hi DiffChange ctermfg=228 ctermbg=58 cterm=NONE
    hi DiffDelete ctermfg=217 ctermbg=52 cterm=NONE
    hi DiffText ctermfg=228 ctermbg=58 cterm=NONE
    hi Directory ctermfg=39 ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermfg=16 ctermbg=NONE cterm=NONE
    hi ErrorMsg ctermfg=231 ctermbg=124 cterm=NONE
    hi FoldColumn ctermfg=250 ctermbg=235 cterm=NONE
    hi Folded ctermfg=115 ctermbg=234 cterm=italic
    hi IncSearch ctermfg=231 ctermbg=94 cterm=reverse
    hi LineNr ctermfg=246 ctermbg=234 cterm=NONE
    hi MatchParen ctermfg=231 ctermbg=31 cterm=NONE
    hi ModeMsg ctermfg=246 ctermbg=NONE cterm=NONE
    hi MoreMsg ctermfg=39 ctermbg=NONE cterm=NONE
    hi NonText ctermfg=246 ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=255 ctermbg=236 cterm=NONE
    hi PmenuSbar ctermfg=16 ctermbg=246 cterm=NONE
    hi PmenuSel ctermfg=231 ctermbg=234 cterm=reverse
    hi PmenuThumb ctermfg=231 ctermbg=16 cterm=NONE
    hi Question ctermfg=39 ctermbg=NONE cterm=NONE
    hi Search ctermfg=231 ctermbg=28 cterm=NONE
    hi SignColumn ctermfg=246 ctermbg=234 cterm=NONE
    hi SpecialKey ctermfg=246 ctermbg=NONE cterm=NONE
    hi SpellBad ctermfg=203 ctermbg=NONE cterm=NONE
    hi SpellCap ctermfg=226 ctermbg=NONE cterm=NONE
    hi SpellLocal ctermfg=75 ctermbg=NONE cterm=NONE
    hi SpellRare ctermfg=115 ctermbg=NONE cterm=NONE
    hi StatusLine ctermfg=255 ctermbg=238 cterm=NONE
    hi StatusLineNC ctermfg=246 ctermbg=236 cterm=NONE
    hi TabLine ctermfg=231 ctermbg=240 cterm=NONE
    hi TabLineFill ctermfg=246 ctermbg=236 cterm=NONE
    hi TabLineSel ctermfg=231 ctermbg=16 cterm=NONE
    hi Title ctermfg=153 ctermbg=NONE cterm=NONE
    hi VertSplit ctermfg=241 ctermbg=241 cterm=NONE
    hi Visual ctermfg=16 ctermbg=153 cterm=NONE
    hi VisualNOS ctermfg=231 ctermbg=182 cterm=NONE
    hi WarningMsg ctermfg=209 ctermbg=NONE cterm=NONE
    hi WildMenu ctermfg=16 ctermbg=221 cterm=NONE
    hi Comment ctermfg=246 ctermbg=NONE cterm=italic
    hi Constant ctermfg=212 ctermbg=NONE cterm=NONE
    hi Error ctermfg=231 ctermbg=124 cterm=reverse
    hi Identifier ctermfg=44 ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=231 ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=211 ctermbg=NONE cterm=NONE
    hi Special ctermfg=79 ctermbg=NONE cterm=NONE
    hi Statement ctermfg=147 ctermbg=NONE cterm=NONE
    hi Todo ctermfg=218 ctermbg=NONE cterm=bold
    hi Type ctermfg=79 ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=153 ctermbg=NONE cterm=NONE
    hi String ctermfg=39 ctermbg=NONE cterm=NONE
    hi Quote ctermfg=117 ctermbg=NONE cterm=NONE
    hi CursorIM ctermfg=231 ctermbg=16 cterm=NONE
    hi ToolbarLine ctermfg=246 ctermbg=241 cterm=NONE
    hi ToolbarButton ctermfg=16 ctermbg=251 cterm=bold
    hi jsObjectKey ctermfg=212 ctermbg=NONE cterm=NONE
    hi jsObjectValue ctermfg=182 ctermbg=NONE cterm=NONE
    hi jsObjectProp ctermfg=115 ctermbg=NONE cterm=NONE
    hi jsTemplateExpression ctermfg=79 ctermbg=NONE cterm=NONE
    hi jsModuleKeyword ctermfg=115 ctermbg=NONE cterm=NONE
    hi javaScriptParens ctermfg=80 ctermbg=NONE cterm=NONE
    hi jsTemplateBraces ctermfg=180 ctermbg=NONE cterm=NONE
    hi jsDestructuringBraces ctermfg=180 ctermbg=NONE cterm=NONE
    hi jsBrackets ctermfg=180 ctermbg=NONE cterm=NONE
    hi jsBraces ctermfg=180 ctermbg=NONE cterm=NONE
    hi jsParens ctermfg=180 ctermbg=NONE cterm=NONE
    hi jsFuncParens ctermfg=180 ctermbg=NONE cterm=NONE
    hi jsClassBraces ctermfg=180 ctermbg=NONE cterm=NONE
    hi jsFuncBraces ctermfg=180 ctermbg=NONE cterm=NONE
    hi jsObjectBraces ctermfg=180 ctermbg=NONE cterm=NONE
    hi jsRepeatBraces ctermfg=180 ctermbg=NONE cterm=NONE
    hi jsIfElseBraces ctermfg=180 ctermbg=NONE cterm=NONE
    hi jsTryCatchBraces ctermfg=180 ctermbg=NONE cterm=NONE
    hi jsVariableDef ctermfg=212 ctermbg=NONE cterm=NONE
    hi NERDTreeFile ctermfg=79 ctermbg=NONE cterm=NONE
    if !s:italics
      hi Folded cterm=NONE
      hi Comment cterm=NONE
    endif
  else
    " Light background
    if get(g:, 'modus_transp_bg', 0)
      hi Normal ctermfg=16 ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=16 ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=16 ctermbg=231 cterm=NONE
      hi Terminal ctermfg=16 ctermbg=231 cterm=NONE
    endif
    hi ColorColumn ctermfg=16 ctermbg=231 cterm=NONE
    hi Conceal ctermfg=94 ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=231 ctermbg=88 cterm=NONE
    hi CursorColumn ctermfg=NONE ctermbg=189 cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=189 cterm=NONE
    hi CursorLineNr ctermfg=232 ctermbg=254 cterm=NONE
    hi DiffAdd ctermfg=22 ctermbg=194 cterm=NONE
    hi DiffChange ctermfg=94 ctermbg=222 cterm=NONE
    hi DiffDelete ctermfg=88 ctermbg=224 cterm=NONE
    hi DiffText ctermfg=94 ctermbg=222 cterm=NONE
    hi Directory ctermfg=19 ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermfg=231 ctermbg=NONE cterm=NONE
    hi ErrorMsg ctermfg=16 ctermbg=210 cterm=NONE
    hi FoldColumn ctermfg=238 ctermbg=255 cterm=NONE
    hi Folded ctermfg=23 ctermbg=255 cterm=italic
    hi IncSearch ctermfg=16 ctermbg=220 cterm=reverse
    hi LineNr ctermfg=240 ctermbg=255 cterm=NONE
    hi MatchParen ctermfg=16 ctermbg=117 cterm=NONE
    hi ModeMsg ctermfg=240 ctermbg=NONE cterm=NONE
    hi MoreMsg ctermfg=19 ctermbg=NONE cterm=NONE
    hi NonText ctermfg=240 ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=232 ctermbg=254 cterm=NONE
    hi PmenuSbar ctermfg=231 ctermbg=240 cterm=NONE
    hi PmenuSel ctermfg=16 ctermbg=255 cterm=reverse
    hi PmenuThumb ctermfg=16 ctermbg=231 cterm=NONE
    hi Question ctermfg=19 ctermbg=NONE cterm=NONE
    hi Search ctermfg=16 ctermbg=114 cterm=NONE
    hi SignColumn ctermfg=240 ctermbg=255 cterm=NONE
    hi SpecialKey ctermfg=240 ctermbg=NONE cterm=NONE
    hi SpellBad ctermfg=160 ctermbg=NONE cterm=NONE
    hi SpellCap ctermfg=100 ctermbg=NONE cterm=NONE
    hi SpellLocal ctermfg=19 ctermbg=NONE cterm=NONE
    hi SpellRare ctermfg=23 ctermbg=NONE cterm=NONE
    hi StatusLine ctermfg=232 ctermbg=251 cterm=NONE
    hi StatusLineNC ctermfg=240 ctermbg=254 cterm=NONE
    hi TabLine ctermfg=236 ctermbg=251 cterm=NONE
    hi TabLineFill ctermfg=240 ctermbg=254 cterm=NONE
    hi TabLineSel ctermfg=16 ctermbg=231 cterm=NONE
    hi Title ctermfg=25 ctermbg=NONE cterm=NONE
    hi VertSplit ctermfg=247 ctermbg=247 cterm=NONE
    hi Visual ctermfg=231 ctermbg=25 cterm=NONE
    hi VisualNOS ctermfg=16 ctermbg=90 cterm=NONE
    hi WarningMsg ctermfg=88 ctermbg=NONE cterm=NONE
    hi WildMenu ctermfg=231 ctermbg=130 cterm=NONE
    hi Comment ctermfg=240 ctermbg=NONE cterm=italic
    hi Constant ctermfg=89 ctermbg=NONE cterm=NONE
    hi Error ctermfg=16 ctermbg=210 cterm=reverse
    hi Identifier ctermfg=24 ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=16 ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=88 ctermbg=NONE cterm=NONE
    hi Special ctermfg=23 ctermbg=NONE cterm=NONE
    hi Statement ctermfg=55 ctermbg=NONE cterm=NONE
    hi Todo ctermfg=89 ctermbg=NONE cterm=bold
    hi Type ctermfg=23 ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=25 ctermbg=NONE cterm=NONE
    hi String ctermfg=19 ctermbg=NONE cterm=NONE
    hi Quote ctermfg=24 ctermbg=NONE cterm=NONE
    hi CursorIM ctermfg=16 ctermbg=231 cterm=NONE
    hi ToolbarLine ctermfg=240 ctermbg=247 cterm=NONE
    hi ToolbarButton ctermfg=231 ctermbg=237 cterm=bold
    hi jsObjectKey ctermfg=89 ctermbg=NONE cterm=NONE
    hi jsObjectValue ctermfg=90 ctermbg=NONE cterm=NONE
    hi jsObjectProp ctermfg=23 ctermbg=NONE cterm=NONE
    hi jsTemplateExpression ctermfg=23 ctermbg=NONE cterm=NONE
    hi jsModuleKeyword ctermfg=23 ctermbg=NONE cterm=NONE
    hi javaScriptParens ctermfg=25 ctermbg=NONE cterm=NONE
    hi jsTemplateBraces ctermfg=94 ctermbg=NONE cterm=NONE
    hi jsDestructuringBraces ctermfg=94 ctermbg=NONE cterm=NONE
    hi jsBrackets ctermfg=94 ctermbg=NONE cterm=NONE
    hi jsBraces ctermfg=94 ctermbg=NONE cterm=NONE
    hi jsParens ctermfg=94 ctermbg=NONE cterm=NONE
    hi jsFuncParens ctermfg=94 ctermbg=NONE cterm=NONE
    hi jsClassBraces ctermfg=94 ctermbg=NONE cterm=NONE
    hi jsFuncBraces ctermfg=94 ctermbg=NONE cterm=NONE
    hi jsObjectBraces ctermfg=94 ctermbg=NONE cterm=NONE
    hi jsRepeatBraces ctermfg=94 ctermbg=NONE cterm=NONE
    hi jsIfElseBraces ctermfg=94 ctermbg=NONE cterm=NONE
    hi jsTryCatchBraces ctermfg=94 ctermbg=NONE cterm=NONE
    hi jsVariableDef ctermfg=89 ctermbg=NONE cterm=NONE
    hi NERDTreeFile ctermfg=23 ctermbg=NONE cterm=NONE
    if !s:italics
      hi Folded cterm=NONE
      hi Comment cterm=NONE
    endif
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 0
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi PopupSelected term=reverse
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  hi debugBreakpoint term=reverse
  hi debugPC term=reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: bg_main #000000 ~ Black
" Color: bg_dim #1e1e1e ~ Black
" Color: bg_alt #0f0f0f ~ LightGrey
" Color: fg_main #ffffff ~ White
" Color: fg_dim #989898 ~ White
" Color: fg_alt #c6daff ~ White
" Color: border #646464 ~ DarkGrey
" Color: border_highlight #C4C4C4 ~ White
" Color: red #ff5f59 ~ DarkRed
" Color: red_warmer #ff6b55 ~ LightRed
" Color: red_cooler #ff7f9f ~ DarkRed
" Color: red_faint #ff9580 ~ LightRed
" Color: green #44bc44 ~ DarkGreen
" Color: green_warmer #70b900 ~ LightGreen
" Color: green_cooler #00c06f ~ DarkGreen
" Color: green_faint #88ca9f ~ LightGreen
" Color: yellow #d0bc00 ~ DarkYellow
" Color: yellow_warmer #fec43f ~ LightYellow
" Color: yellow_cooler #dfaf7a ~ DarkYellow
" Color: yellow_faint #D2B580 ~ LightYellow
" Color: blue #2fafff ~ DarkBlue
" Color: blue_warmer #79a8ff ~ LightBlue
" Color: blue_cooler #00bcff ~ DarkBlue
" Color: blue_faint #82b0ec ~ LightBlue
" Color: magenta #feacd0 ~ DarkMagenta
" Color: magenta_warmer #f78fe7 ~ LightMagenta
" Color: magenta_cooler #b6a0ff ~ DarkMagenta
" Color: magenta_faint #caa6df ~ LightMagenta
" Color: cyan #00d3d0 ~ DarkCyan
" Color: cyan_warmer #4ae2f0 ~ LightCyan
" Color: cyan_cooler #6ae4b9 ~ DarkCyan
" Color: cyan_faint #9ac8e0 ~ LightCyan
" Color: rust #db7b5f ~ LightYellow
" Color: gold #c0965b ~ DarkYellow
" Color: olive #9cbd6f ~ LightGreen
" Color: slate #76afbf ~ DarkGreen
" Color: indigo #9099d9 ~ LightMagenta
" Color: maroon #cf7fa7 ~ DarkMagenta
" Color: pink #d09dc0 ~ LightMagenta
" Color: red_intense #ff5f5f ~ LightRed
" Color: green_intense #44df44 ~ LightGreen
" Color: yellow_intense #efef00 ~ LightYellow
" Color: blue_intense #338fff ~ LightBlue
" Color: magenta_intense #ff66ff ~ LightMagenta
" Color: cyan_intense #00eff0 ~ LightCyan
" Color: bg_red_intense #9d1f1f ~ DarkRed
" Color: bg_green_intense #2f822f ~ DarkGreen
" Color: bg_yellow_intense #7a6100 ~ DarkYellow
" Color: bg_blue_intense #1640b0 ~ DarkBlue
" Color: bg_magenta_intense #7030af ~ DarkMagenta
" Color: bg_cyan_intense #2266ae ~ DarkCyan
" Color: bg_red_subtle #620f2a ~ DarkRed
" Color: bg_green_subtle #00422a ~ DarkGreen
" Color: bg_yellow_subtle #4a4000 ~ DarkYellow
" Color: bg_blue_subtle #242679 ~ DarkBlue
" Color: bg_magenta_subtle #552f5f ~ DarkMagenta
" Color: bg_cyan_subtle #004065 ~ DarkCyan
" Color: bg_red_nuanced #2c0614 ~ LightRed
" Color: bg_green_nuanced #001904 ~ LightGreen
" Color: bg_yellow_nuanced #221000 ~ LightYellow
" Color: bg_blue_nuanced #0f0e39 ~ LightBlue
" Color: bg_magenta_nuanced #230631 ~ LightMagenta
" Color: bg_cyan_nuanced #041529 ~ LightCyan
" Color: bg_completion #2f447f ~ DarkBLue
" Color: bg_hl_line #2f3849 ~ DarkGreen
" Color: bg_paren_match #2f7f9f ~ LightBlue
" Color: bg_paren_expression #453040 ~ DarkGray
" Color: bg_char_0 #0050af ~ LightBlue
" Color: bg_char_1 #7f1f7f ~ LightMagenta
" Color: bg_char_2 #625a00 ~ DarkYellow
" Color: bg_active #303030 ~ Black
" Color: fg_active #f4f4f4 ~ White
" Color: bg_inactive #282828 ~ DarkGray
" Color: fg_inactive #bfc0c4 ~ LightGray
" Color: bg_status_line_active #404040 ~ DarkGray
" Color: fg_status_line_active #f0f0f0 ~ LightGray
" Color: bg_status_line_inactive #2d2d2d ~ DarkGray
" Color: fg_status_line_inactive #969696 ~ LightGray
" Color: bg_tab_bar #313131 ~ DarkGray
" Color: bg_tab_current #000000 ~ DarkBlue
" Color: bg_tab_other #545454 ~ DarkGray
" Color: fg_tab_other #f7f7f7 ~ LightGray
" Color: bg_tab_alternate #545490 ~ DarkGray
" Color: bg_added #00381f ~ DarkGreen
" Color: bg_added_faint #002910 ~ LightGreen
" Color: bg_added_refine #034f2f ~ DarkGreen
" Color: bg_added_fringe #237f3f ~ LightGreen
" Color: fg_added #a0e0a0 ~ LightGreen
" Color: fg_added_intense #80e080 ~ LightGreen
" Color: bg_changed #363300 ~ DarkYellow
" Color: bg_changed_faint #2a1f00 ~ LightYellow
" Color: bg_changed_refine #4a4a00 ~ DarkYellow
" Color: bg_changed_fringe #8a7a00 ~ LightYellow
" Color: fg_changed #efef80 ~ LightYellow
" Color: fg_changed_intense #c0b05f ~ LightYellow
" Color: bg_removed #4f1119 ~ DarkRed
" Color: bg_removed_faint #380a0f ~ DarkRed
" Color: bg_removed_refine #781a1f ~ LightRed
" Color: bg_removed_fringe #b81a1f ~ LightRed
" Color: fg_removed #ffbfbf ~ DarkRed
" Color: fg_removed_intense #ff9095 ~ DarkRed
" Color: bg_diff_context #1a1a1a ~ Black
" Term colors: bg_main red green yellow blue magenta cyan fg_main
" Term colors: bg_alt red_warmer green_warmer yellow_warmer
" Term colors: blue_warmer magenta_warmer cyan_warmer fg_alt
" Background: dark
" Background: light
" Color: bg_main #ffffff ~
" Color: bg_dim #f2f2f2 ~
" Color: bg_alt #f0f0f0 ~
" Color: fg_main #000000 ~
" Color: fg_dim #595959 ~
" Color: fg_alt #193668 ~
" Color: border #9f9f9f ~
" Color: border_highlight #3b3b3b ~
" Color: red #a60000 ~
" Color: red_warmer #972500 ~
" Color: red_cooler #a0132f ~
" Color: red_faint #7f0000 ~
" Color: green #006800 ~
" Color: green_warmer #316500 ~
" Color: green_cooler #00663f ~
" Color: green_faint #2a5045 ~
" Color: yellow #6f5500 ~
" Color: yellow_warmer #884900 ~
" Color: yellow_cooler #7a4f2f ~
" Color: yellow_faint #624416 ~
" Color: blue #0031a9 ~
" Color: blue_warmer #3548cf ~
" Color: blue_cooler #0000b0 ~
" Color: blue_faint #003497 ~
" Color: magenta #721045 ~
" Color: magenta_warmer #8f0075 ~
" Color: magenta_cooler #531ab6 ~
" Color: magenta_faint #7c318f ~
" Color: cyan #005e8b ~
" Color: cyan_warmer #3f578f ~
" Color: cyan_cooler #005f5f ~
" Color: cyan_faint #005077 ~
" Color: rust #8a290f ~
" Color: gold #80601f ~
" Color: olive #56692d ~
" Color: slate #2f3f83 ~
" Color: indigo #4a3a8a ~
" Color: maroon #731c52 ~
" Color: pink #7b435c ~
" Color: red_intense #d00000 ~
" Color: green_intense #008900 ~
" Color: yellow_intense #808000 ~
" Color: blue_intense #0000ff ~
" Color: magenta_intense #dd22dd ~
" Color: cyan_intense #008899 ~
" Color: bg_red_intense #ff8f88 ~
" Color: bg_green_intense #8adf80 ~
" Color: bg_yellow_intense #f3d000 ~
" Color: bg_blue_intense #bfc9ff ~
" Color: bg_magenta_intense #dfa0f0 ~
" Color: bg_cyan_intense #a4d5f9 ~
" Color: bg_red_subtle #ffcfbf ~
" Color: bg_green_subtle #b3fabf ~
" Color: bg_yellow_subtle #fff576 ~
" Color: bg_blue_subtle #ccdfff ~
" Color: bg_magenta_subtle #ffddff ~
" Color: bg_cyan_subtle #bfefff ~
" Color: bg_red_nuanced #fff1f0 ~
" Color: bg_green_nuanced #ecf7ed ~
" Color: bg_yellow_nuanced #fff3da ~
" Color: bg_blue_nuanced #f3f3ff ~
" Color: bg_magenta_nuanced #fdf0ff ~
" Color: bg_cyan_nuanced #ebf6fa ~
" Color: bg_completion #c0deff ~
" Color: bg_hl_line #d0d6ec ~
" Color: bg_paren_match #5fcfff ~
" Color: bg_paren_expression #efd3f5 ~
" Color: bg_char_0 #7feaff ~
" Color: bg_char_1 #ffaaff ~
" Color: bg_char_2 #dff000 ~
" Color: bg_active #e0e0e0 ~
" Color: fg_active #0a0a0a ~
" Color: bg_inactive #e9e9e9 ~
" Color: fg_inactive #404148 ~
" Color: bg_status_line_active #c8c8c8 ~
" Color: fg_status_line_active #0a0a0a ~
" Color: bg_status_line_inactive #e6e6e6 ~
" Color: fg_status_line_inactive #585858 ~
" Color: bg_tab_bar #dfdfdf ~
" Color: bg_tab_current #ffffff ~
" Color: bg_tab_other #c2c2c2 ~
" Color: fg_tab_other #333333 ~
" Color: bg_tab_alternate #c2c2e8 ~
" Color: bg_added #c1f2d1 ~
" Color: bg_added_faint #d8f8e1 ~
" Color: bg_added_refine #aee5be ~
" Color: bg_added_fringe #6cc06c ~
" Color: fg_added #005000 ~
" Color: fg_added_intense #006700 ~
" Color: bg_changed #ffdfa9 ~
" Color: bg_changed_faint #ffefbf ~
" Color: bg_changed_refine #fac090 ~
" Color: bg_changed_fringe #d7c20a ~
" Color: fg_changed #553d00 ~
" Color: fg_changed_intense #655000 ~
" Color: bg_removed #ffd8d5 ~
" Color: bg_removed_faint #ffe9e9 ~
" Color: bg_removed_refine #f3b5af ~
" Color: bg_removed_fringe #d84a4f ~
" Color: fg_removed #8f1313 ~
" Color: fg_removed_intense #aa2222 ~
" Color: bg_diff_context #f3f3f3 ~
" Term colors: bg_main red green yellow blue magenta cyan fg_main
" Term colors: bg_alt red_warmer green_warmer yellow_warmer
" Term colors: blue_warmer magenta_warmer cyan_warmer fg_alt
" Background: light
" Background: any
" vim: et ts=8 sw=2 sts=2
