tap "d12frosted/emacs-plus"
brew "coreutils"
brew "fd"
brew "fzf"
brew "htop"
brew "jq"
brew "ripgrep"
brew "starship"
brew "stow"
brew "tldr"
brew "tmux"
brew "tree"
brew "wget"
brew "d12frosted/emacs-plus/emacs-plus@31", args: ["without-cocoa"]
cask "font-fira-code-nerd-font"
